### ISSUE TITLE
Merge fork?

### ISSUE THREAD

**Issue by davelab6** [sehgalvibhor/webconfusion#9]
@crusher95 what is the status of your fork at https://github.com/crusher95/webconfusion ? Will it be merged to this upstream? :)

**Comment by crusher95** [comment]
Ideally it should be merged but since the development on the project halted suddenly, I am not sure what is going to happen.Though I would be really interested in continuing development on the same. @davelab6

**Comment by sehgalvibhor** [comment]
The thought is mutual. If we can move forward with this activity, We can
make some major improvements.

**Comment by sehgalvibhor** [comment]
Closing because of no response.
